name: Robo Shop Workflow in gihub actions

on:
  push:
    branches:
      - main

concurrency:
  group: pr-validation-${{ github.ref}}
  cancel-in-progress: true

env:
  REPO_NAME: gnishanth777/robo_shop_application

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

  build-service:
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        service:
          - cart
          - catalogue
          - user
          - shipping
          - payment
          - frontend
    uses: ./.github/workflows/docker-build-push-workflow.yml
    secrets: inherit
    with:
      repo_name: ${{ env.REPO_NAME }}
      service: ${{ matrix.service }}
      service_path: ${{ matrix.service }}

  docker-compose:
    needs: build-service
    uses: ./github/workflows/docker-compose-intregration.yml
    secrets: inherit
    with:
      compose_file: compose/docker-compose-integration-dev.yml
      repo_name: ${{ env.REPO_NAME }}




